post:
    path:     /
    defaults: { _controller: BlogPostBundle:Post:index }

post_new:
    path:     /new
    defaults: { _controller: BlogPostBundle:Post:new }

post_create:
    path:     /create
    defaults: { _controller: BlogPostBundle:Post:create }

post_show:
    path:     /show/{id}
    defaults: { _controller: BlogPostBundle:Post:show, id: 1 }
    requirements:
        id: \d+

post_edit:
    path:     /{id}/edit
    defaults: { _controller: BlogPostBundle:Post:edit }

post_delete:
    path:     /{id}/delete
    defaults: { _controller: BlogPostBundle:Post:delete }
