<?php

namespace Blog\PostBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findThird()
    {
      $qb = $this->createQueryBuilder('p');

      $qb
        ->where('p.id = :id')
        ->setParameter('id', 3)
      ;

      return $qb
        ->getQuery()
        ->getResult()
      ;
    }
}
